### ISSUE TITLE
Administrator template and styles

### ISSUE THREAD

**Issue by vivekraghuram** [calblueprint/revolv#67] opened 2014-11-09 01:39 UTC

**Comment by noahsark769** [comment] 2015-01-19 22:38
The initial version of this seems to be done, am I right about that @vivekraghuram?

**Comment by vivekraghuram** [comment] 2015-01-19 22:47
Yeah although there's some more functionality to add.

**Comment by noahsark769** [comment] 2015-01-21 02:23
Okay cool. I'm gunna close this as it's technically a duplicate of #66

**Closed by noahsark769** 2015-01-21 02:23 UTC
Labels: feature
