### ISSUE TITLE
Installation guide is incorrect

### ISSUE THREAD

**Issue by inakrin** [calblueprint/revolv#393] opened 2015-10-08 16:29 UTC
There is something wrong with the installation guide here https://github.com/calblueprint/revolv/blob/master/README.md
I've performed all steps from "If using vagrant:" section and application fails with the error:   
>
> NoAuthHandlerFound at /
> No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV1Handler'] Check your credentials

**Comment by noahsark769** [comment] 2015-10-08 16:56
@philipn: Were you able to figure out a good workflow for getting the topcoders working on this? The problem is that there's no `.revolv_bash_profile` and as such, AWS and Paypal API keys are not getting set. Maybe we should generate test API keys for the topcoders to use?

@inakrin: Sorry you're run into this, we really should have documented this before. A brute-force fix for this is to sign up for an Amazon AWS account and a Paypal developer account, create an Amazon s3 bucket, then find the API keys for Amazon and Paypal, and create a file called `.revolv_bash_profile` with the following content:

```
export AWS_ACCESS_KEY_ID=...your access key...
export AWS_SECRET_ACCESS_KEY=...your secret key...
export AWS_STORAGE_BUCKET_NAME=...your s3 bucket name...
export PAYPAL_MODE=sandbox
export PAYPAL_CLIENT_ID=...your paypal id...
export PAYPAL_CLIENT_SECRET=...your paypal secret key...
```

This file is gitignored (since in different environments it contains sensitive information) but it is used by the vmanage.py script to set up the environment for the app to run in. Hopefully, this will fix the issue. Let me know if I can help more!

**Comment by philipn** [comment] 2015-10-08 17:41
I've got a fix for this but forgot to push it. Should be fixed in a minute.

**Comment by philipn** [comment] 2015-10-08 17:56
@inakrin Sorry about that! If you do a `git pull` you should have a version that doesn't require AWS and PayPal keys to run.

**Comment by noahsark769** [comment] 2015-10-09 02:53
@inakrin did the fix work for you? If so, we can close this issue :D

**Closed** 2015-10-29 22:06 UTC
Labels: priority-1
